set(_AMENT_PACKAGE_NAME "remote_controller")
set(remote_controller_VERSION "0.0.0")
set(remote_controller_MAINTAINER "linux <linux@todo.todo>")
set(remote_controller_BUILD_DEPENDS "rclcpp" "std_msgs" "communication" "yaml-cpp")
set(remote_controller_BUILDTOOL_DEPENDS "ament_cmake")
set(remote_controller_BUILD_EXPORT_DEPENDS "rclcpp" "std_msgs" "communication" "yaml-cpp")
set(remote_controller_BUILDTOOL_EXPORT_DEPENDS )
set(remote_controller_EXEC_DEPENDS "ament_index_python" "ros2launch" "rclcpp" "std_msgs" "communication" "yaml-cpp")
set(remote_controller_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(remote_controller_GROUP_DEPENDS )
set(remote_controller_MEMBER_OF_GROUPS )
set(remote_controller_DEPRECATED "")
set(remote_controller_EXPORT_TAGS)
list(APPEND remote_controller_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
