set(_AMENT_PACKAGE_NAME "bxi_depth_camera")
set(bxi_depth_camera_VERSION "0.1.0")
set(bxi_depth_camera_MAINTAINER "liufq <popsay@163.com>")
set(bxi_depth_camera_BUILD_DEPENDS "rclcpp" "rcl_interfaces" "sensor_msgs" "opencv")
set(bxi_depth_camera_BUILDTOOL_DEPENDS "ament_cmake")
set(bxi_depth_camera_BUILD_EXPORT_DEPENDS "rclcpp" "rcl_interfaces" "sensor_msgs" "opencv")
set(bxi_depth_camera_BUILDTOOL_EXPORT_DEPENDS )
set(bxi_depth_camera_EXEC_DEPENDS "libusb-1.0" "libudev-dev" "ros2launch" "rclcpp" "rcl_interfaces" "sensor_msgs" "opencv")
set(bxi_depth_camera_TEST_DEPENDS "ament_cmake_gtest")
set(bxi_depth_camera_GROUP_DEPENDS )
set(bxi_depth_camera_MEMBER_OF_GROUPS )
set(bxi_depth_camera_DEPRECATED "")
set(bxi_depth_camera_EXPORT_TAGS)
list(APPEND bxi_depth_camera_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
